-- AlterTable
ALTER TABLE "Card" ADD COLUMN IF NOT EXISTS "allowSmartExchange" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "CardDailyStats" ADD COLUMN IF NOT EXISTS "nfcVisits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CardDailyStats" ADD COLUMN IF NOT EXISTS "qrVisits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CardDailyStats" ADD COLUMN IF NOT EXISTS "walletVisits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CardDailyStats" ADD COLUMN IF NOT EXISTS "directVisits" INTEGER NOT NULL DEFAULT 0;
