import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_BACKGROUND,
  DEFAULT_FONTS,
  DEFAULT_THEME,
} from "../types/card";

export function createBusinessCard(): CardDocument {
  const cx = W / 2;
  const elements: CardElement[] = [
    {
      id: "watermark",
      type: "text",
      x: 40,
      y: H - 200,
      width: 400,
      height: 140,
      zIndex: 0,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "BUSINESS\nCARD",
        placeholder: "BUSINESS\nCARD",
        fontFamily: "System",
        fontSize: 64,
        fontWeight: "800",
        color: "#E8E8E8",
        textAlign: "left",
        letterSpacing: 2,
        maxLines: 2,
        autoScale: false,
        opacity: 1,
        lineHeight: 68,
      },
    },
    {
      id: "logo",
      type: "image",
      x: cx - 80,
      y: 120,
      width: 160,
      height: 160,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      image: {
        uri: null,
        placeholderText: "YOUR\nLOGO\nHERE",
        borderRadius: 80,
        objectFit: "cover",
        borderWidth: 1.5,
        borderColor: "#D9D9D9",
        borderStyle: "dashed",
      },
    },
    {
      id: "businessName",
      type: "text",
      x: 60,
      y: 330,
      width: W - 120,
      height: 60,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "BUSINESS NAME",
        fontFamily: "System",
        fontSize: 42,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 2,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "personName",
      type: "text",
      x: 60,
      y: 400,
      width: W - 120,
      height: 44,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Your Full Name",
        fontFamily: "System",
        fontSize: 24,
        fontWeight: "400",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 1,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "jobTitle",
      type: "text",
      x: 60,
      y: 448,
      width: W - 120,
      height: 36,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Job Title",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "400",
        color: "#999999",
        textAlign: "center",
        letterSpacing: 1,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "divider1",
      type: "divider",
      x: 60,
      y: 510,
      width: W - 120,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: {
        shapeType: "line",
        fill: "transparent",
        stroke: "#E5E5E5",
        strokeWidth: 1,
        strokeDasharray: "",
        borderRadius: 0,
      },
    },
    {
      id: "emailLabel",
      type: "text",
      x: 60,
      y: 530,
      width: W - 120,
      height: 24,
      zIndex: 2,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "EMAIL",
        placeholder: "EMAIL",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "emailValue",
      type: "text",
      x: 60,
      y: 556,
      width: W - 120,
      height: 32,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "email@example.com",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "400",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "phoneLabel",
      type: "text",
      x: 60,
      y: 604,
      width: W - 120,
      height: 24,
      zIndex: 2,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "PHONE",
        placeholder: "PHONE",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "phoneValue",
      type: "text",
      x: 60,
      y: 630,
      width: W - 120,
      height: 32,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "+61 400 000 000",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "400",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "websiteLabel",
      type: "text",
      x: 60,
      y: 678,
      width: W - 120,
      height: 24,
      zIndex: 2,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "WEBSITE",
        placeholder: "WEBSITE",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "websiteValue",
      type: "text",
      x: 60,
      y: 704,
      width: W - 120,
      height: 32,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "www.example.com",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "400",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "qrLabel",
      type: "text",
      x: 60,
      y: 760,
      width: W - 120,
      height: 20,
      zIndex: 2,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "SCAN TO CONNECT",
        placeholder: "SCAN TO CONNECT",
        fontFamily: "System",
        fontSize: 10,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "exchangeQR",
      type: "qr",
      x: cx - 70,
      y: 790,
      width: 140,
      height: 140,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      qr: {
        value: "",
        size: 140,
        color: "#000000",
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#E5E5E5",
      },
    },
    {
      id: "nfcIcon",
      type: "icon",
      x: cx - 20,
      y: 955,
      width: 40,
      height: 40,
      zIndex: 2,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "nfc", size: 36, color: "#000000", strokeWidth: 2 },
    },
    {
      id: "nfc",
      type: "nfc",
      x: cx - 100,
      y: 1000,
      width: 200,
      height: 50,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      nfc: {
        label: "NFC",
        value: "",
        style: "dashed",
        iconColor: "#000000",
        textColor: "#CFCFCF",
        borderColor: "#E5E5E5",
      },
    },
  ];

  return {
    templateId: "business",
    canvasWidth: W,
    canvasHeight: H,
    background: { ...DEFAULT_BACKGROUND },
    theme: { ...DEFAULT_THEME },
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
