import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_BACKGROUND,
  DEFAULT_FONTS,
  DEFAULT_THEME,
} from "../types/card";

export function createCoupon(): CardDocument {
  const cx = W / 2;
  const pad = 60;
  const iw = W - pad * 2;

  const elements: CardElement[] = [
    {
      id: "tagIcon",
      type: "icon",
      x: cx - 24,
      y: 60,
      width: 48,
      height: 48,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "tag", size: 44, color: "#000000", strokeWidth: 2 },
    },
    {
      id: "title",
      type: "text",
      x: pad,
      y: 120,
      width: iw,
      height: 40,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "COUPON",
        placeholder: "COUPON",
        fontFamily: "System",
        fontSize: 32,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 6,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "offerDivLeft",
      type: "divider",
      x: pad,
      y: 200,
      width: iw * 0.28,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#D9D9D9", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "offerLabel",
      type: "text",
      x: pad + iw * 0.28,
      y: 188,
      width: iw * 0.44,
      height: 26,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "EXCLUSIVE OFFER",
        placeholder: "EXCLUSIVE OFFER",
        fontFamily: "System",
        fontSize: 12,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "offerDivRight",
      type: "divider",
      x: pad + iw * 0.72,
      y: 200,
      width: iw * 0.28,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#D9D9D9", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "heroValue",
      type: "text",
      x: pad,
      y: 250,
      width: iw,
      height: 160,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "20%",
        fontFamily: "System",
        fontSize: 120,
        fontWeight: "800",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "offText",
      type: "text",
      x: pad,
      y: 410,
      width: iw,
      height: 50,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "OFF",
        fontFamily: "System",
        fontSize: 40,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 12,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "subtext",
      type: "text",
      x: pad,
      y: 468,
      width: iw,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "ON YOUR NEXT PURCHASE",
        fontFamily: "System",
        fontSize: 13,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "perforation",
      type: "perforation",
      x: 0,
      y: 530,
      width: W,
      height: 30,
      zIndex: 2,
      locked: true,
      visible: true,
      rotation: 0,
      perforation: { color: "#D9D9D9", dotSize: 4, gap: 6, cutoutRadius: 15 },
    },
    {
      id: "redeemLabel",
      type: "text",
      x: pad,
      y: 590,
      width: iw,
      height: 26,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "TAP TO REDEEM",
        placeholder: "TAP TO REDEEM",
        fontFamily: "System",
        fontSize: 12,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "nfcBox",
      type: "nfc",
      x: cx - 130,
      y: 630,
      width: 260,
      height: 120,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      nfc: { label: "NFC", value: "", style: "dashed", iconColor: "#000000", textColor: "#CFCFCF", borderColor: "#D9D9D9" },
    },
    {
      id: "validIcon",
      type: "icon",
      x: cx - 120,
      y: 790,
      width: 20,
      height: 20,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "calendar", size: 18, color: "#CFCFCF", strokeWidth: 1.5 },
    },
    {
      id: "validLabel",
      type: "text",
      x: cx - 94,
      y: 790,
      width: 220,
      height: 22,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "VALID UNTIL  31 DEC 2025",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "left",
        letterSpacing: 2,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "divider2",
      type: "divider",
      x: pad,
      y: 840,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "terms",
      type: "text",
      x: pad,
      y: 860,
      width: iw,
      height: 60,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "Valid in-store and online. One-time use only.\nNot valid with other offers or promotions.",
        placeholder: "Valid in-store and online. One-time use only.\nNot valid with other offers or promotions.",
        fontFamily: "System",
        fontSize: 10,
        fontWeight: "400",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 0,
        maxLines: 3,
        autoScale: false,
        opacity: 1,
        lineHeight: 16,
      },
    },
  ];

  return {
    templateId: "coupon",
    canvasWidth: W,
    canvasHeight: H,
    background: { ...DEFAULT_BACKGROUND },
    theme: { ...DEFAULT_THEME },
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
