import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_BACKGROUND,
  DEFAULT_FONTS,
  DEFAULT_THEME,
} from "../types/card";

export function createEventTicket(): CardDocument {
  const cx = W / 2;
  const pad = 60;
  const iw = W - pad * 2;

  const elements: CardElement[] = [
    {
      id: "ticketIcon",
      type: "icon",
      x: cx - 24,
      y: 60,
      width: 48,
      height: 48,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "ticket", size: 44, color: "#000000", strokeWidth: 2 },
    },
    {
      id: "title",
      type: "text",
      x: pad,
      y: 118,
      width: iw,
      height: 44,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "EVENT TICKET",
        placeholder: "EVENT TICKET",
        fontFamily: "System",
        fontSize: 32,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "eventLabel",
      type: "text",
      x: pad,
      y: 195,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "EVENT",
        placeholder: "EVENT",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "left",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "eventValue",
      type: "text",
      x: pad,
      y: 218,
      width: iw,
      height: 36,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Your Event Name",
        fontFamily: "System",
        fontSize: 26,
        fontWeight: "600",
        color: "#000000",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "dateLabel",
      type: "text",
      x: pad,
      y: 272,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "DATE & TIME",
        placeholder: "DATE & TIME",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "left",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "dateValue",
      type: "text",
      x: pad,
      y: 296,
      width: iw,
      height: 32,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Sat, 24 May 2025 \u2022 7:00 PM",
        fontFamily: "System",
        fontSize: 20,
        fontWeight: "500",
        color: "#000000",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "venueLabel",
      type: "text",
      x: pad,
      y: 346,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "VENUE",
        placeholder: "VENUE",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "left",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "venueValue",
      type: "text",
      x: pad,
      y: 370,
      width: iw,
      height: 32,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Your Venue Name",
        fontFamily: "System",
        fontSize: 20,
        fontWeight: "500",
        color: "#000000",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "addressValue",
      type: "text",
      x: pad,
      y: 404,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "123 Main Street, City",
        fontFamily: "System",
        fontSize: 14,
        fontWeight: "400",
        color: "#999999",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "divider1",
      type: "divider",
      x: pad,
      y: 450,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    // Ticket info row — 4 columns
    {
      id: "sectionLabel",
      type: "text",
      x: pad,
      y: 470,
      width: 170,
      height: 20,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "SECTION", placeholder: "SECTION", fontFamily: "System", fontSize: 10, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 2, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "sectionValue",
      type: "text",
      x: pad,
      y: 492,
      width: 170,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "VIP", fontFamily: "System", fontSize: 22, fontWeight: "700", color: "#000000", textAlign: "center", letterSpacing: 0, maxLines: 1, autoScale: true, opacity: 1 },
    },
    {
      id: "rowLabel",
      type: "text",
      x: pad + 195,
      y: 470,
      width: 170,
      height: 20,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "ROW", placeholder: "ROW", fontFamily: "System", fontSize: 10, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 2, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "rowValue",
      type: "text",
      x: pad + 195,
      y: 492,
      width: 170,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "A", fontFamily: "System", fontSize: 22, fontWeight: "700", color: "#000000", textAlign: "center", letterSpacing: 0, maxLines: 1, autoScale: true, opacity: 1 },
    },
    {
      id: "seatLabel",
      type: "text",
      x: pad + 390,
      y: 470,
      width: 150,
      height: 20,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "SEAT", placeholder: "SEAT", fontFamily: "System", fontSize: 10, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 2, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "seatValue",
      type: "text",
      x: pad + 390,
      y: 492,
      width: 150,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "12", fontFamily: "System", fontSize: 22, fontWeight: "700", color: "#000000", textAlign: "center", letterSpacing: 0, maxLines: 1, autoScale: true, opacity: 1 },
    },
    {
      id: "typeLabel",
      type: "text",
      x: pad + 555,
      y: 470,
      width: 165,
      height: 20,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "TYPE", placeholder: "TYPE", fontFamily: "System", fontSize: 10, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 2, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "typeValue",
      type: "text",
      x: pad + 555,
      y: 492,
      width: 165,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "ADULT", fontFamily: "System", fontSize: 22, fontWeight: "700", color: "#000000", textAlign: "center", letterSpacing: 0, maxLines: 1, autoScale: true, opacity: 1 },
    },
    {
      id: "perforation",
      type: "perforation",
      x: 0,
      y: 545,
      width: W,
      height: 30,
      zIndex: 2,
      locked: true,
      visible: true,
      rotation: 0,
      perforation: { color: "#D9D9D9", dotSize: 4, gap: 6, cutoutRadius: 15 },
    },
    {
      id: "ticketIdLabel",
      type: "text",
      x: pad,
      y: 600,
      width: iw,
      height: 20,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "TICKET ID", placeholder: "TICKET ID", fontFamily: "System", fontSize: 10, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 3, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "ticketIdValue",
      type: "text",
      x: pad,
      y: 622,
      width: iw,
      height: 26,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "TKT-2025-00001", fontFamily: "System", fontSize: 16, fontWeight: "500", color: "#000000", textAlign: "center", letterSpacing: 1, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "qrCode",
      type: "qr",
      x: cx - 100,
      y: 668,
      width: 200,
      height: 200,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      qr: { value: "https://oryx.app/ticket", size: 200, color: "#000000", backgroundColor: "#FFFFFF", borderRadius: 8, borderWidth: 1, borderColor: "#E5E5E5" },
    },
    {
      id: "footerIcon",
      type: "icon",
      x: pad,
      y: 895,
      width: 18,
      height: 18,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "info", size: 16, color: "#CFCFCF", strokeWidth: 1.5 },
    },
    {
      id: "footerNote",
      type: "text",
      x: pad + 24,
      y: 893,
      width: iw - 24,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "Please present this ticket at the entrance.", placeholder: "Please present this ticket at the entrance.", fontFamily: "System", fontSize: 11, fontWeight: "400", color: "#CFCFCF", textAlign: "left", letterSpacing: 0, maxLines: 1, autoScale: false, opacity: 1 },
    },
  ];

  return {
    templateId: "eventTicket",
    canvasWidth: W,
    canvasHeight: H,
    background: { ...DEFAULT_BACKGROUND },
    theme: { ...DEFAULT_THEME },
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
