import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_BACKGROUND,
  DEFAULT_FONTS,
  DEFAULT_THEME,
} from "../types/card";

export function createGenericCard(): CardDocument {
  const cx = W / 2;
  const pad = 60;
  const iw = W - pad * 2;

  const elements: CardElement[] = [
    {
      id: "heading",
      type: "text",
      x: pad,
      y: 70,
      width: iw,
      height: 46,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "YOUR HEADING",
        fontFamily: "System",
        fontSize: 34,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "subheading",
      type: "text",
      x: pad,
      y: 124,
      width: iw,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Your Subheading Goes Here",
        fontFamily: "System",
        fontSize: 16,
        fontWeight: "400",
        color: "#999999",
        textAlign: "center",
        letterSpacing: 1,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "heroImage",
      type: "image",
      x: pad,
      y: 185,
      width: iw,
      height: 360,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      image: {
        uri: null,
        placeholderText: "YOUR IMAGE HERE",
        borderRadius: 16,
        objectFit: "cover",
        borderWidth: 1,
        borderColor: "#E5E5E5",
        borderStyle: "solid",
      },
    },
    {
      id: "divider1",
      type: "divider",
      x: pad,
      y: 575,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "qrLabel",
      type: "text",
      x: pad,
      y: 598,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "SCAN TO VIEW",
        placeholder: "SCAN TO VIEW",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "qrCode",
      type: "qr",
      x: cx - 90,
      y: 636,
      width: 180,
      height: 180,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      qr: { value: "https://oryx.app", size: 180, color: "#000000", backgroundColor: "#FFFFFF", borderRadius: 8, borderWidth: 1, borderColor: "#E5E5E5" },
    },
    {
      id: "divider2",
      type: "divider",
      x: pad,
      y: 845,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "nfcLabel",
      type: "text",
      x: pad,
      y: 868,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "TAP TO INTERACT",
        placeholder: "TAP TO INTERACT",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "nfcBox",
      type: "nfc",
      x: cx - 120,
      y: 904,
      width: 240,
      height: 90,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      nfc: { label: "NFC", value: "", style: "dashed", iconColor: "#000000", textColor: "#CFCFCF", borderColor: "#D9D9D9" },
    },
  ];

  return {
    templateId: "generic",
    canvasWidth: W,
    canvasHeight: H,
    background: { ...DEFAULT_BACKGROUND },
    theme: { ...DEFAULT_THEME },
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
