import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_BACKGROUND,
  DEFAULT_FONTS,
  DEFAULT_THEME,
} from "../types/card";

export function createGiftCard(): CardDocument {
  const cx = W / 2;
  const pad = 60;
  const iw = W - pad * 2;

  const elements: CardElement[] = [
    {
      id: "giftIcon",
      type: "icon",
      x: cx - 24,
      y: 60,
      width: 48,
      height: 48,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "gift", size: 44, color: "#000000", strokeWidth: 2 },
    },
    {
      id: "title",
      type: "text",
      x: pad,
      y: 120,
      width: iw,
      height: 40,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "GIFT CARD",
        placeholder: "GIFT CARD",
        fontFamily: "System",
        fontSize: 32,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 6,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "subtitle",
      type: "text",
      x: pad,
      y: 168,
      width: iw,
      height: 26,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "A GIFT FOR YOU",
        placeholder: "A GIFT FOR YOU",
        fontFamily: "System",
        fontSize: 12,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "divider1",
      type: "divider",
      x: pad,
      y: 220,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "balanceLabel",
      type: "text",
      x: pad,
      y: 250,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "CARD BALANCE",
        placeholder: "CARD BALANCE",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "balanceValue",
      type: "text",
      x: pad,
      y: 286,
      width: iw,
      height: 120,
      zIndex: 2,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "$100",
        fontFamily: "System",
        fontSize: 96,
        fontWeight: "800",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "balanceWords",
      type: "text",
      x: pad,
      y: 410,
      width: iw,
      height: 26,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "ONE HUNDRED DOLLARS",
        fontFamily: "System",
        fontSize: 12,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "divider2",
      type: "divider",
      x: pad,
      y: 464,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "codeLabel",
      type: "text",
      x: pad,
      y: 490,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "CARD CODE",
        placeholder: "CARD CODE",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "qrCode",
      type: "qr",
      x: cx - 110,
      y: 530,
      width: 220,
      height: 220,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      qr: { value: "https://oryx.app/gift", size: 220, color: "#000000", backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E5E5E5" },
    },
    {
      id: "validIcon",
      type: "icon",
      x: cx - 120,
      y: 785,
      width: 20,
      height: 20,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "calendar", size: 18, color: "#CFCFCF", strokeWidth: 1.5 },
    },
    {
      id: "validLabel",
      type: "text",
      x: cx - 94,
      y: 785,
      width: 220,
      height: 22,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "VALID UNTIL  31 DEC 2025",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "left",
        letterSpacing: 2,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "divider3",
      type: "divider",
      x: pad,
      y: 835,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "terms",
      type: "text",
      x: pad,
      y: 855,
      width: iw,
      height: 60,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "Redeem in-store or online.\nThis card cannot be exchanged for cash.",
        placeholder: "Redeem in-store or online.\nThis card cannot be exchanged for cash.",
        fontFamily: "System",
        fontSize: 10,
        fontWeight: "400",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 0,
        maxLines: 3,
        autoScale: false,
        opacity: 1,
        lineHeight: 16,
      },
    },
  ];

  return {
    templateId: "giftCard",
    canvasWidth: W,
    canvasHeight: H,
    background: { ...DEFAULT_BACKGROUND },
    theme: { ...DEFAULT_THEME },
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
