import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_BACKGROUND,
  DEFAULT_FONTS,
  DEFAULT_THEME,
} from "../types/card";

export function createGymClassPassCard(): CardDocument {
  const cx = W / 2;
  const pad = 60;
  const iw = W - pad * 2;

  const elements: CardElement[] = [
    {
      id: "gymIcon",
      type: "icon",
      x: cx - 24,
      y: 55,
      width: 48,
      height: 48,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "dumbbell", size: 44, color: "#000000", strokeWidth: 2 },
    },
    {
      id: "title",
      type: "text",
      x: pad,
      y: 115,
      width: iw,
      height: 40,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "CLASS PASS",
        placeholder: "CLASS PASS",
        fontFamily: "System",
        fontSize: 30,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 5,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "subtitle",
      type: "text",
      x: pad,
      y: 162,
      width: iw,
      height: 26,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "GROUP FITNESS SESSIONS",
        placeholder: "GROUP FITNESS SESSIONS",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "businessName",
      type: "text",
      x: pad,
      y: 198,
      width: iw,
      height: 32,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Studio / Gym Name",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "600",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 1,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "divider1",
      type: "divider",
      x: pad,
      y: 250,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: {
        shapeType: "line",
        fill: "",
        stroke: "#E5E5E5",
        strokeWidth: 1,
        strokeDasharray: "",
        borderRadius: 0,
      },
    },
    {
      id: "memberLabel",
      type: "text",
      x: pad,
      y: 272,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "MEMBER",
        placeholder: "MEMBER",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "left",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "memberName",
      type: "text",
      x: pad,
      y: 296,
      width: iw,
      height: 34,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Member Full Name",
        fontFamily: "System",
        fontSize: 24,
        fontWeight: "600",
        color: "#000000",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "classTypeLabel",
      type: "text",
      x: pad,
      y: 348,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "CLASS TYPE",
        placeholder: "CLASS TYPE",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "left",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "classType",
      type: "text",
      x: pad,
      y: 372,
      width: iw,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "HIIT · Yoga · Spin",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "600",
        color: "#000000",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "divider2",
      type: "divider",
      x: pad,
      y: 424,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: {
        shapeType: "line",
        fill: "",
        stroke: "#E5E5E5",
        strokeWidth: 1,
        strokeDasharray: "",
        borderRadius: 0,
      },
    },
    {
      id: "sessionsLabel",
      type: "text",
      x: pad,
      y: 446,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "SESSIONS REMAINING",
        placeholder: "SESSIONS REMAINING",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "sessionStamps",
      type: "stampRow",
      x: pad + 20,
      y: 482,
      width: iw - 40,
      height: 60,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      stampRow: {
        total: 10,
        filled: 7,
        filledStyle: "dot",
        filledColor: "#000000",
        emptyColor: "#D9D9D9",
        size: 40,
      },
    },
    {
      id: "sessionCount",
      type: "text",
      x: pad,
      y: 556,
      width: iw,
      height: 26,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "7 OF 10 SESSIONS",
        placeholder: "7 OF 10 SESSIONS",
        fontFamily: "System",
        fontSize: 13,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 2,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "divider3",
      type: "divider",
      x: pad,
      y: 604,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: {
        shapeType: "line",
        fill: "",
        stroke: "#E5E5E5",
        strokeWidth: 1,
        strokeDasharray: "",
        borderRadius: 0,
      },
    },
    {
      id: "expiryLabel",
      type: "text",
      x: pad,
      y: 626,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "EXPIRES",
        placeholder: "EXPIRES",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "expiryDate",
      type: "text",
      x: pad,
      y: 650,
      width: iw,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "30 Jun 2026",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "600",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 1,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "tapLabel",
      type: "text",
      x: pad,
      y: 708,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "TAP TO REDEEM",
        placeholder: "TAP TO REDEEM",
        fontFamily: "System",
        fontSize: 12,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "nfcBox",
      type: "nfc",
      x: cx - 120,
      y: 744,
      width: 240,
      height: 100,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      nfc: {
        label: "NFC",
        value: "",
        style: "dashed",
        iconColor: "#000000",
        textColor: "#CFCFCF",
        borderColor: "#D9D9D9",
      },
    },
  ];

  return {
    templateId: "gymClassPass",
    canvasWidth: W,
    canvasHeight: H,
    background: { ...DEFAULT_BACKGROUND },
    theme: { ...DEFAULT_THEME },
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
