import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_FONTS,
  type BackgroundConfig,
  type ThemeConfig,
} from "../types/card";

const GYM_BG: BackgroundConfig = {
  mode: "color",
  color: "#0f172a",
  imageUri: null,
  overlayOpacity: 0,
};

const GYM_THEME: ThemeConfig = {
  primaryTextColor: "#f8fafc",
  secondaryTextColor: "#94a3b8",
  dividerColor: "#334155",
  accentColor: "#ef4444",
};

export function createGymMembershipCard(): CardDocument {
  const cx = W / 2;
  const pad = 60;
  const iw = W - pad * 2;
  const label = (content: string) => ({
    content,
    placeholder: content,
    fontFamily: "System",
    fontSize: 11,
    fontWeight: "600" as const,
    color: "#94a3b8",
    textAlign: "left" as const,
    letterSpacing: 3,
    maxLines: 1,
    autoScale: false,
    opacity: 1,
  });

  const elements: CardElement[] = [
    {
      id: "gymIcon",
      type: "icon",
      x: cx - 24,
      y: 55,
      width: 48,
      height: 48,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "dumbbell", size: 44, color: "#ef4444", strokeWidth: 2 },
    },
    {
      id: "title",
      type: "text",
      x: pad,
      y: 115,
      width: iw,
      height: 40,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "GYM MEMBERSHIP",
        placeholder: "GYM MEMBERSHIP",
        fontFamily: "System",
        fontSize: 28,
        fontWeight: "700",
        color: "#f8fafc",
        textAlign: "center",
        letterSpacing: 5,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "businessName",
      type: "text",
      x: pad,
      y: 162,
      width: iw,
      height: 36,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Your Gym Name",
        fontFamily: "System",
        fontSize: 20,
        fontWeight: "600",
        color: "#f8fafc",
        textAlign: "center",
        letterSpacing: 2,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "divider1",
      type: "divider",
      x: pad,
      y: 220,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: {
        shapeType: "line",
        fill: "",
        stroke: "#334155",
        strokeWidth: 1,
        strokeDasharray: "",
        borderRadius: 0,
      },
    },
    {
      id: "memberLabel",
      type: "text",
      x: pad,
      y: 248,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: label("MEMBER"),
    },
    {
      id: "memberName",
      type: "text",
      x: pad,
      y: 272,
      width: iw,
      height: 36,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Member Full Name",
        fontFamily: "System",
        fontSize: 26,
        fontWeight: "600",
        color: "#f8fafc",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "tierLabel",
      type: "text",
      x: pad,
      y: 328,
      width: iw / 2 - 8,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: label("TIER"),
    },
    {
      id: "membershipTier",
      type: "text",
      x: pad,
      y: 352,
      width: iw / 2 - 8,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "Unlimited",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "600",
        color: "#ef4444",
        textAlign: "left",
        letterSpacing: 1,
        maxLines: 1,
        autoScale: true,
        opacity: 1,
      },
    },
    {
      id: "memberIdLabel",
      type: "text",
      x: cx + 8,
      y: 328,
      width: iw / 2 - 8,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { ...label("MEMBER ID"), textAlign: "right" },
    },
    {
      id: "memberIdValue",
      type: "text",
      x: cx + 8,
      y: 352,
      width: iw / 2 - 8,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "GYM-001234",
        fontFamily: "System",
        fontSize: 18,
        fontWeight: "500",
        color: "#f8fafc",
        textAlign: "right",
        letterSpacing: 1,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "divider2",
      type: "divider",
      x: pad,
      y: 408,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: {
        shapeType: "line",
        fill: "",
        stroke: "#334155",
        strokeWidth: 1,
        strokeDasharray: "",
        borderRadius: 0,
      },
    },
    {
      id: "expiryLabel",
      type: "text",
      x: pad,
      y: 432,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: label("VALID UNTIL"),
    },
    {
      id: "expiryDate",
      type: "text",
      x: pad,
      y: 456,
      width: iw,
      height: 32,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: {
        content: "",
        placeholder: "31 Dec 2026",
        fontFamily: "System",
        fontSize: 22,
        fontWeight: "600",
        color: "#f8fafc",
        textAlign: "left",
        letterSpacing: 0,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "divider3",
      type: "divider",
      x: pad,
      y: 516,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: {
        shapeType: "line",
        fill: "",
        stroke: "#334155",
        strokeWidth: 1,
        strokeDasharray: "",
        borderRadius: 0,
      },
    },
    {
      id: "tapLabel",
      type: "text",
      x: pad,
      y: 540,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "TAP TO CHECK IN",
        placeholder: "TAP TO CHECK IN",
        fontFamily: "System",
        fontSize: 12,
        fontWeight: "600",
        color: "#94a3b8",
        textAlign: "center",
        letterSpacing: 4,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "nfcBox",
      type: "nfc",
      x: cx - 120,
      y: 576,
      width: 240,
      height: 100,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      nfc: {
        label: "NFC",
        value: "",
        style: "dashed",
        iconColor: "#ef4444",
        textColor: "#94a3b8",
        borderColor: "#334155",
      },
    },
    {
      id: "checkInQr",
      type: "qr",
      x: cx - 80,
      y: 710,
      width: 160,
      height: 160,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      qr: {
        value: "https://oryx.app/check-in",
        size: 160,
        color: "#f8fafc",
        backgroundColor: "#0f172a",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#334155",
      },
    },
    {
      id: "qrLabel",
      type: "text",
      x: pad,
      y: 886,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "SCAN FOR CHECK-IN",
        placeholder: "SCAN FOR CHECK-IN",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#94a3b8",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
  ];

  return {
    templateId: "gymMembership",
    canvasWidth: W,
    canvasHeight: H,
    background: GYM_BG,
    theme: GYM_THEME,
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
