import type { CardDocument, CardElement } from "../types/card";
import {
  CANVAS_WIDTH as W,
  CANVAS_HEIGHT as H,
  DEFAULT_BACKGROUND,
  DEFAULT_FONTS,
  DEFAULT_THEME,
} from "../types/card";

export function createLoyaltyCard(): CardDocument {
  const cx = W / 2;
  const pad = 60;
  const iw = W - pad * 2;

  const elements: CardElement[] = [
    {
      id: "starIcon",
      type: "icon",
      x: cx - 24,
      y: 55,
      width: 48,
      height: 48,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "star", size: 44, color: "#000000", strokeWidth: 2 },
    },
    {
      id: "title",
      type: "text",
      x: pad,
      y: 115,
      width: iw,
      height: 40,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "LOYALTY CARD",
        placeholder: "LOYALTY CARD",
        fontFamily: "System",
        fontSize: 30,
        fontWeight: "700",
        color: "#000000",
        textAlign: "center",
        letterSpacing: 5,
        maxLines: 1,
        autoScale: false,
        opacity: 1,
      },
    },
    {
      id: "subtitle",
      type: "text",
      x: pad,
      y: 162,
      width: iw,
      height: 44,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: {
        content: "THANK YOU FOR BEING\nA VALUED MEMBER",
        placeholder: "THANK YOU FOR BEING\nA VALUED MEMBER",
        fontFamily: "System",
        fontSize: 11,
        fontWeight: "600",
        color: "#CFCFCF",
        textAlign: "center",
        letterSpacing: 3,
        maxLines: 2,
        autoScale: false,
        opacity: 1,
        lineHeight: 18,
      },
    },
    {
      id: "divider1",
      type: "divider",
      x: pad,
      y: 228,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "memberLabel",
      type: "text",
      x: pad,
      y: 250,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "MEMBER", placeholder: "MEMBER", fontFamily: "System", fontSize: 11, fontWeight: "600", color: "#CFCFCF", textAlign: "left", letterSpacing: 3, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "memberName",
      type: "text",
      x: pad,
      y: 274,
      width: iw,
      height: 34,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "Your Full Name", fontFamily: "System", fontSize: 24, fontWeight: "600", color: "#000000", textAlign: "left", letterSpacing: 0, maxLines: 1, autoScale: true, opacity: 1 },
    },
    {
      id: "memberIdLabel",
      type: "text",
      x: pad,
      y: 322,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "MEMBER ID", placeholder: "MEMBER ID", fontFamily: "System", fontSize: 11, fontWeight: "600", color: "#CFCFCF", textAlign: "left", letterSpacing: 3, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "memberIdValue",
      type: "text",
      x: pad,
      y: 346,
      width: iw,
      height: 28,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "MEM-001234", fontFamily: "System", fontSize: 18, fontWeight: "500", color: "#000000", textAlign: "left", letterSpacing: 1, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "divider2",
      type: "divider",
      x: pad,
      y: 396,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "progressLabel",
      type: "text",
      x: pad,
      y: 418,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "YOUR PROGRESS", placeholder: "YOUR PROGRESS", fontFamily: "System", fontSize: 11, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 3, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "stamps",
      type: "stampRow",
      x: pad + 40,
      y: 456,
      width: iw - 80,
      height: 60,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      stampRow: { total: 5, filled: 4, filledStyle: "star", filledColor: "#000000", emptyColor: "#D9D9D9", size: 48 },
    },
    {
      id: "stampCount",
      type: "text",
      x: pad,
      y: 530,
      width: iw,
      height: 26,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "4 OF 5 STAMPS", placeholder: "4 OF 5 STAMPS", fontFamily: "System", fontSize: 13, fontWeight: "700", color: "#000000", textAlign: "center", letterSpacing: 2, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "stampHelper",
      type: "text",
      x: pad,
      y: 558,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "Earn 1 more stamp to get your reward!", placeholder: "Earn 1 more stamp to get your reward!", fontFamily: "System", fontSize: 12, fontWeight: "400", color: "#999999", textAlign: "center", letterSpacing: 0, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "divider3",
      type: "divider",
      x: pad,
      y: 604,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "tapLabel",
      type: "text",
      x: pad,
      y: 626,
      width: iw,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "TAP TO USE", placeholder: "TAP TO USE", fontFamily: "System", fontSize: 12, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 4, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "nfcBox",
      type: "nfc",
      x: cx - 120,
      y: 662,
      width: 240,
      height: 100,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      nfc: { label: "NFC", value: "", style: "dashed", iconColor: "#000000", textColor: "#CFCFCF", borderColor: "#D9D9D9" },
    },
    {
      id: "divider4",
      type: "divider",
      x: pad,
      y: 790,
      width: iw,
      height: 1,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      shape: { shapeType: "line", fill: "", stroke: "#E5E5E5", strokeWidth: 1, strokeDasharray: "", borderRadius: 0 },
    },
    {
      id: "rewardIcon",
      type: "icon",
      x: cx - 12,
      y: 812,
      width: 24,
      height: 24,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      icon: { name: "gift", size: 22, color: "#000000", strokeWidth: 1.5 },
    },
    {
      id: "rewardLabel",
      type: "text",
      x: pad,
      y: 842,
      width: iw,
      height: 22,
      zIndex: 1,
      locked: true,
      visible: true,
      rotation: 0,
      text: { content: "REWARD", placeholder: "REWARD", fontFamily: "System", fontSize: 11, fontWeight: "600", color: "#CFCFCF", textAlign: "center", letterSpacing: 3, maxLines: 1, autoScale: false, opacity: 1 },
    },
    {
      id: "rewardValue",
      type: "text",
      x: pad,
      y: 866,
      width: iw,
      height: 30,
      zIndex: 1,
      locked: false,
      visible: true,
      rotation: 0,
      text: { content: "", placeholder: "10% OFF YOUR NEXT PURCHASE", fontFamily: "System", fontSize: 16, fontWeight: "600", color: "#000000", textAlign: "center", letterSpacing: 2, maxLines: 1, autoScale: true, opacity: 1 },
    },
  ];

  return {
    templateId: "loyaltyCard",
    canvasWidth: W,
    canvasHeight: H,
    background: { ...DEFAULT_BACKGROUND },
    theme: { ...DEFAULT_THEME },
    fonts: { ...DEFAULT_FONTS },
    elements,
  };
}
